global using Juan_NET.Application.Authorization;
global using Juan_NET.Domain.Entities;
global using Juan_NET.Infrastructure;
global using Juan_NET.Infrastructure.Database;
global using Juan_NET.Infrastructure.Payments;
global using Juan_NET.Infrastructure.Services;
global using Juan_NET.Persistence;
global using Juan_NET.Persistence.Context;
global using Juan_NET.Web.Services;
global using Juan_NET.Web.ViewModels;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Localization;
global using PromotionCodeListOptions = Stripe.PromotionCodeListOptions;
global using PromotionCodeService = Stripe.PromotionCodeService;
global using Session = Stripe.Checkout.Session;
global using SessionCreateOptions = Stripe.Checkout.SessionCreateOptions;
global using SessionDiscountOptions = Stripe.Checkout.SessionDiscountOptions;
global using SessionLineItemOptions = Stripe.Checkout.SessionLineItemOptions;
global using SessionLineItemPriceDataOptions = Stripe.Checkout.SessionLineItemPriceDataOptions;
global using SessionLineItemPriceDataProductDataOptions = Stripe.Checkout.SessionLineItemPriceDataProductDataOptions;
global using SessionService = Stripe.Checkout.SessionService;
global using StripeConfiguration = Stripe.StripeConfiguration;
global using System.ComponentModel.DataAnnotations;
global using System.Globalization;
global using System.Linq.Expressions;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text.Json;
