<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Juan_NET.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Juan-NET.Domain\Juan-NET.Domain.csproj" />
    <ProjectReference Include="..\Juan-NET.Persistence\Juan-NET.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="View\View Model\" />
    <Folder Include="View\Admin\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
